#!/bin/bash

script_dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

annovar_dir="/home/jessada/development/scilifelab/tools/annovar/"
convert2annovar_script=$annovar_dir/convert2annovar.pl


tmp_dir="$script_dir/tmp"
tmp_prefix="$tmp_dir/tmp_"
#tmp_avdb2="$tmp_dir/tmp_avdb2"
#tmp_avdb="$tmp_dir/tmp_avdb"
#---------- input --------------
patient_code=$1
#vcf_file=$1
chr=$2
raw_region=$3
header_file=$4
tabix_file=$5
out=$6

#---------- get region of interest --------------
start_pos="$( sed -n 1p $raw_region | awk -F'\t' '{printf "%s", $3}' )"
end_pos="$( sed -n 2p $raw_region | awk -F'\t' '{printf "%s", $4}' )"

#---------- parse the region of interest and convert it into avdb format --------------
#grep -i $patient_code $header_file

col=`grep -i $patient_code $header_file | awk -va="$patient_code" 'BEGIN{}
END{}
{
    for(i=1;i<=NF;i++){
        IGNORECASE = 1
        if ( tolower($i) == tolower(a))
            {print i }
    }
}'`

echo
echo $col

tabix $tabix_file $chr:$start_pos-$end_pos | cut -f1-9,$col | grep -v "\./\." | grep -v "0/0" > $tmp_prefix"$patient_code"_avdb
$convert2annovar_script -format vcf4 $tmp_prefix"$patient_code"_avdb > $out
#grep "1/1" $tmp_avdb1 | awk '{printf "%s\t%s\t%s\t%s\t%s\tHom|%s|%s\n", $1, $2, $2, $3, $4, $5, $6}' > $tmp_avdb2
#grep -v "1/1" $tmp_avdb1 | awk '{printf "%s\t%s\t%s\t%s\t%s\tHet|%s|%s\n", $1, $2, $2, $3, $4, $5, $6}' >> $tmp_avdb2
#sort -k1,2 $tmp_avdb2 > $out
#echo $out



#tabix $tabix_file $chr:$start_pos-$end_pos | awk -vc=$col -F'\t' '{printf "%s\t%s\t%s\t%s\t%s\t%s\n", $1, $2, $2, $4, $5, c}' > $tmp_avdb1
#grep "1/1" $tmp_avdb1 | awk '{printf "%s\tHom\n", $0}' > $tmp_avdb2
#grep "0/1" $tmp_avdb1 | awk '{printf "%s\tHet\n", $0}' >> $tmp_avdb2
#tabix $vcf_file $chr:$start_pos-$end_pos > tmp_vcf
#tabix $vcf_file $chr:$start_pos-$end_pos | grep "1/1" | awk '{printf "%s\t%s\t%s\t%s\t%s\tHom|%s|%s\n", $1, $2, $2, $4, $5, $6, $7}' > $tmp_avdb
#tabix $vcf_file $chr:$start_pos-$end_pos | grep "0/1" | awk '{printf "%s\t%s\t%s\t%s\t%s\tHet|%s|%s\n", $1, $2, $2, $4, $5, $6, $7}' >> $tmp_avdb

#tabix $vcf_file $chr:$start_pos-$end_pos | grep "1/1" | awk '{printf "%s\t%s\t%s\t%s\t%s\tHom\n", $1, $2, $2, $4, $5}' > $tmp_avdb
#tabix $vcf_file $chr:$start_pos-$end_pos | grep "0/1" | awk '{printf "%s\t%s\t%s\t%s\t%s\tHet\n", $1, $2, $2, $4, $5}' >> $tmp_avdb
#sort -k1,2 $tmp_avdb > $out




