#!/bin/bash

script_dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

annovar_dir="/home/jessada/development/scilifelab/tools/annovar/"
summarize_annovar_script=$annovar_dir/summarize_annovar.pl
human_db_dir=$annovar_dir/humandb/

#---------- input --------------
avdb_file=$1
out=$2

#---------- annotate --------------
$summarize_annovar_script -out $out -buildver hg19 -verdbsnp 137 -ver1000g 1000g2012apr -veresp 6500 -remove -alltranscript $avdb_file $human_db_dir



