#!/bin/bash

script_dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

vcf_dir="/home/jessada/development/CMM/master_data/CRC_screen4/idx"

#---------- code of the members to analyze --------------
header_file=$1
tabix_file=$2
chr=$3
region_out=$4
family_code=$5
member_code[1]=$6
if [ $# -eq 6 ]; then
    member_code[2]=dummy2
    member_code[3]=dummy3
else
    if [ $# -eq 7 ]; then
        member_code[2]=$7
        member_code[3]=dummy3
    else
        member_code[2]=$7
        member_code[3]=$8
    fi
fi

#---------- script location --------------
vcf2avdb_script=$script_dir/020_vcf2avdb
summarize_script=$script_dir/030_summarize
comma2tab_script=$script_dir/040_comma2tab
find_common_mutations_script=$script_dir/050_find_common_mutations
csvs2xls=$script_dir/060_csvs2xls.py

#---------- tmp data location --------------
tmp_dir="$script_dir/tmp"
#tmp_prefix="$tmp_dir/chr$chr"

#---------- output location --------------
out_dir="$script_dir/../out"
family_dir="$out_dir/family$family_code"_"chr$chr"

if [ ! -d "$family_dir" ]; then
    mkdir "$family_dir"
fi

member1_out="$family_dir/${member_code[1]}.tab.csv"
member2_out="$family_dir/${member_code[2]}.tab.csv"
member3_out="$family_dir/${member_code[3]}.tab.csv"
common_mutations_out="$family_dir/fam$family_code"_"common_mutations.tab.csv"
xls_out="$family_dir/fam$family_code"_chr"$chr".xls

#---------- analyze --------------

rm $tmp_dir/*

for (( i=1; i<=$(($#-5)); i++ ))
do
    vcf_file="$vcf_dir/fam$family_code"-"${member_code[$i]}.vcf.gz"
    avdb_tmp_file="$tmp_dir/${member_code[$i]}.avdb"
    summarize_out="$tmp_dir/${member_code[$i]}.summarize"
    csv_file=$summarize_out".genome_summary.csv"
    tmp_tab=$summarize_out".genome_summary.csv.tab.csv"

    $vcf2avdb_script ${member_code[$i]} $chr $region_out $header_file $tabix_file $avdb_tmp_file
    $summarize_script $avdb_tmp_file $summarize_out
    $comma2tab_script $csv_file $tmp_tab
done

csv1="$tmp_dir/${member_code[1]}.summarize.genome_summary.csv.tab.csv"
csv2="$tmp_dir/${member_code[2]}.summarize.genome_summary.csv.tab.csv"
csv3="$tmp_dir/${member_code[3]}.summarize.genome_summary.csv.tab.csv"

cp $csv1 $member1_out

if [ $# -eq 6 ]; then
    python $csvs2xls $csv1 ${member_code[1]} $xls_out
else
    cp $csv2 $member2_out

    if [ $# -eq 7 ]; then
        $find_common_mutations_script $csv1 ${member_code[1]} $csv2 ${member_code[2]} $common_mutations_out

        python $csvs2xls $csv1 ${member_code[1]} $csv2 ${member_code[2]} $common_mutations_out $xls_out
    else
        if [ $# -eq 8 ]; then
            $find_common_mutations_script $csv1 ${member_code[1]} $csv2 ${member_code[2]} $csv3 ${member_code[3]} $common_mutations_out

            cp $csv3 $member3_out

            python $csvs2xls $csv1 ${member_code[1]} $csv2 ${member_code[2]} $csv3 ${member_code[3]} $common_mutations_out $xls_out
        fi
    fi
fi

