#!/bin/bash

script_dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

annovar_dir="/home/jessada/development/scilifelab/tools/annovar/"

#---------- arguments --------------
chr=$1
beginning=$2
ending=$3
tabix_file=$4
working_dir=$5
out_prefix=$6

out_file=$working_dir/$out_prefix".tab.csv"
#---------- arguments --------------

#---------- get region --------------
lookup_data_dir="/home/jessada/development/scilifelab/tools/annovar/humandb"
prefix_ref_db_file="$lookup_data_dir/hg19_snp137"

begin_pos="$( grep -P "$beginning\t" $prefix_ref_db_file"_chr"$chr".txt" | awk -F'\t' '{printf "%s", $3}' )"
end_pos="$( grep -P "$ending\t" $prefix_ref_db_file"_chr"$chr".txt" | awk -F'\t' '{printf "%s", $3}' )"
#---------- get region --------------

#---------- vcf2avdb --------------
convert2annovar_script=$annovar_dir/convert2annovar.pl

tmp_avdb=$working_dir/$out_prefix"_tmp_avdb"
avdb_out=$working_dir/$out_prefix".avdb"

tabix $tabix_file $chr:$begin_pos-$end_pos | cut -f1-10 | awk -F'\t' '{printf "%s\t%s\t%s\t%s\t%s\t%s|%s\t%s\t%s\t%s\t%s\n", $1, $2, $3, $4, $5, $6, $2, $7, $8, $9, $10}'> $tmp_avdb
$convert2annovar_script -format vcf4 $tmp_avdb --comment > $avdb_out
#---------- vcf2avdb --------------

#---------- summarize --------------
summarize_annovar_script=$annovar_dir/summarize_annovar.pl
human_db_dir=$annovar_dir/humandb/
summarize_out=$working_dir/$out_prefix

$summarize_annovar_script -out $summarize_out -buildver hg19 -verdbsnp 137 -ver1000g 1000g2012apr -veresp 6500 -remove -alltranscript $avdb_out $human_db_dir
#---------- summarize --------------

#---------- comma2tab --------------
csv_file=$summarize_out".genome_summary.csv"
perl -pe 'while (s/(,"[^"]+),/\1<COMMA>/g) {1}; s/"//g; s/,/\t/g; s/<COMMA>/,/g' < $csv_file > $out_file
#---------- comma2tab --------------


