import os
import csv
import linkana.settings as lka_const
from linkana.db.test.template import SafeDBTester
from linkana.db.connectors import SummarizeAnnovarDB
from linkana.db.connectors import FamilyDB


class TestSummarizeAnnovarDB(SafeDBTester):

    def __init__(self, test_name):
        SafeDBTester.__init__(self, test_name)

    def setUp(self):
        self.test_class = 'SummarizeAnnovarDB'

    def __create_db_instance(self):
        db = SummarizeAnnovarDB()
        return db

    def test_header(self):
        """ to check if header generated by Summarize_Annovar.pl is correctly read """

        self.init_test(self.current_func_name)
        db = self.__create_db_instance()
        test_file = os.path.join(self.data_dir,
                                 self.current_func_name + '.tab.csv')
        db.open_db(test_file)
        header = db.header
        self.assertEqual(header.key,
                         None,
                         'Incorrect Annovar header key? Header shouldn')
        self.assertEqual(header.func,
                         'Func',
                         'Incorrect Annovar header at "Func" column')
        self.assertEqual(header.gene,
                         'Gene',
                         'Incorrect Annovar header at "Gene" column')
        self.assertEqual(header.exonic_func,
                         'ExonicFunc',
                         'Incorrect Annovar header at "ExonicFunc" column')
        self.assertEqual(header.aa_change,
                         'AAChange',
                         'Incorrect Annovar header at "AAChange" column')
        self.assertEqual(header.conserved,
                         'Conserved',
                         'Incorrect Annovar header at "Conserved" column')
        self.assertEqual(header.seg_dup,
                         'SegDup',
                         'Incorrect Annovar header at "SegDup" column')
        self.assertEqual(header.esp6500_all,
                         'ESP6500_ALL',
                         'Incorrect Annovar header at "ESP6500_ALL" column')
        self.assertEqual(header.maf,
                         '1000g2012apr_ALL',
                         'Incorrect Annovar header at "1000g2012apr_ALL" column')
        self.assertEqual(header.dbsnp137,
                         'dbSNP137',
                         'Incorrect Annovar header at "dbSNP137" column')
        self.assertEqual(header.avsift,
                         'AVSIFT',
                         'Incorrect Annovar header at "AVSIFT" column')
        self.assertEqual(header.ljb_phylop,
                         'LJB_PhyloP',
                         'Incorrect Annovar header at "LJB_PhyloP" column')
        self.assertEqual(header.ljb_phylop_pred,
                         'LJB_PhyloP_Pred',
                         'Incorrect Annovar header at "LJB_PhyloP_Pred" column')
        self.assertEqual(header.ljb_sift,
                         'LJB_SIFT',
                         'Incorrect Annovar header at "LJB_SIFT" column')
        self.assertEqual(header.ljb_sift_pred,
                         'LJB_SIFT_Pred',
                         'Incorrect Annovar header at "LJB_SIFT_Pred" column')
        self.assertEqual(header.ljb_polyphen2,
                         'LJB_PolyPhen2',
                         'Incorrect Annovar header at "LJB_PolyPhen2" column')
        self.assertEqual(header.ljb_polyphen2_pred,
                         'LJB_PolyPhen2_Pred',
                         'Incorrect Annovar header at "LJB_PolyPhen2_Pred" column')
        self.assertEqual(header.ljb_lrt,
                         'LJB_LRT',
                         'Incorrect Annovar header at "LJB_LRT" column')
        self.assertEqual(header.ljb_lrt_pred,
                         'LJB_LRT_Pred',
                         'Incorrect Annovar header at "LJB_LRT_Pred" column')
        self.assertEqual(header.ljb_mt,
                         'LJB_MutationTaster',
                         'Incorrect Annovar header at "LJB_MutationTaster" column')
        self.assertEqual(header.ljb_mt_pred,
                         'LJB_MutationTaster_Pred',
                         'Incorrect Annovar header at "LJB_MutationTaster_Pred" column')
        self.assertEqual(header.ljb_gerp,
                         'LJB_GERP++',
                         'Incorrect Annovar header at "LJB_GERP++" column')
        self.assertEqual(header.chrom,
                         'Chr',
                         'Incorrect Annovar header at "Chr" column')
        self.assertEqual(header.start_pos,
                         'Start',
                         'Incorrect Annovar header at "Start" column')
        self.assertEqual(header.end_pos,
                         'End',
                         'Incorrect Annovar header at "End" column')
        self.assertEqual(header.ref,
                         'Ref',
                         'Incorrect Annovar header at "Ref" column')
        self.assertEqual(header.obs,
                         'Obs',
                         'Incorrect Annovar header at "Obs" column')

    def test_records_count(self):
        """ to check if all records are read """

        self.init_test(self.current_func_name)
        db = self.__create_db_instance()
        test_file = os.path.join(self.data_dir,
                                 self.current_func_name + '.tab.csv')
        db.open_db(test_file)
        self.assertEqual(len(list(db.records)),
                         9,
                         'Incorrect number of records')

    def test_record_content(self):
        """ to check content in each record generated by Summarize_Annovar.pl is correctly read """

        self.init_test(self.current_func_name)
        db = self.__create_db_instance()
        test_file = os.path.join(self.data_dir,
                                 self.current_func_name + '.tab.csv')
        db.open_db(test_file)
        records = db.records
        records.next()
        test_record = records.next()
        self.assertEqual(test_record.key,
                         '18|12702537|T|G',
                         'Incorrect record key')
        self.assertEqual(test_record.func,
                         'exonic',
                         'Incorrect Annovar content at "Func" column')
        self.assertEqual(test_record.gene,
                         'CEP76',
                         'Incorrect Annovar content at "Gene" column')
        self.assertEqual(test_record.exonic_func,
                         'synonymous SNV',
                         'Incorrect Annovar content at "ExonicFunc" column')
        self.assertEqual(test_record.aa_change,
                         'CEP76:NM_001271989:exon4:c.A405C:p.S135S,CEP76:NM_024899:exon5:c.A630C:p.S210S',
                         'Incorrect Annovar content at "AAChange" column')
        self.assertEqual(test_record.conserved,
                         '671;Name=lod=713',
                         'Incorrect Annovar content at "Conserved" column')
        self.assertEqual(test_record.seg_dup,
                         '',
                         'Incorrect Annovar content at "SegDup" column')
        self.assertEqual(test_record.esp6500_all,
                         '0.000308',
                         'Incorrect Annovar content at "ESP6500_ALL" column')
        self.assertEqual(test_record.maf,
                         '0.0014',
                         'Incorrect Annovar content at "1000g2012apr_ALL" column')
        self.assertEqual(test_record.dbsnp137,
                         'rs146647843',
                         'Incorrect Annovar content at "dbSNP137" column')
        self.assertEqual(test_record.avsift,
                         '0.45',
                         'Incorrect Annovar content at "AVSIFT" column')
        self.assertEqual(test_record.ljb_phylop,
                         '0.994193',
                         'Incorrect Annovar content at "LJB_PhyloP" column')
        self.assertEqual(test_record.ljb_phylop_pred,
                         'C',
                         'Incorrect Annovar content at "LJB_PhyloP_Pred" column')
        self.assertEqual(test_record.ljb_sift,
                         '0',
                         'Incorrect Annovar content at "LJB_SIFT" column')
        self.assertEqual(test_record.ljb_sift_pred,
                         'D',
                         'Incorrect Annovar content at "LJB_SIFT_Pred" column')
        self.assertEqual(test_record.ljb_polyphen2,
                         '0.966',
                         'Incorrect Annovar content at "LJB_PolyPhen2" column')
        self.assertEqual(test_record.ljb_polyphen2_pred,
                         'B',
                         'Incorrect Annovar content at "LJB_PolyPhen2_Pred" column')
        self.assertEqual(test_record.ljb_lrt,
                         '1',
                         'Incorrect Annovar content at "LJB_LRT" column')
        self.assertEqual(test_record.ljb_lrt_pred,
                         'D',
                         'Incorrect Annovar content at "LJB_LRT_Pred" column')
        self.assertEqual(test_record.ljb_mt,
                         '0.999744',
                         'Incorrect Annovar content at "LJB_MutationTaster" column')
        self.assertEqual(test_record.ljb_mt_pred,
                         'D',
                         'Incorrect Annovar content at "LJB_MutationTaster_Pred" column')
        self.assertEqual(test_record.ljb_gerp,
                         '4.62',
                         'Incorrect Annovar content at "LJB_GERP++" column')
        self.assertEqual(test_record.chrom,
                         '18',
                         'Incorrect Annovar content at "Chr" column')
        self.assertEqual(test_record.start_pos,
                         '12697298',
                         'Incorrect Annovar content at "Start" column')
        self.assertEqual(test_record.end_pos,
                         '12697298',
                         'Incorrect Annovar content at "End" column')
        self.assertEqual(test_record.ref,
                         'T',
                         'Incorrect Annovar content at "Ref" column')
        self.assertEqual(test_record.obs,
                         'G',
                         'Incorrect Annovar content at "Obs" column')


class TestFamilyDB(SafeDBTester):

    def __init__(self, test_name):
        SafeDBTester.__init__(self, test_name)

    def setUp(self):
        self.test_class = 'FamilyDB'

    def __create_db_instance(self):
        db = FamilyDB()
        return db

    def test_records_count(self):
        """ to check if all records are read """

        self.init_test(self.current_func_name)
        db = self.__create_db_instance()
        test_file = os.path.join(self.data_dir,
                                 self.current_func_name + '.txt')
        db.open_db(test_file)
        self.assertEqual(len(list(db.records)),
                         7,
                         'Incorrect number of records retrieved by FamilyDB')

    def test_records(self):
        """ to see if FamilyDB can correctly retrieve family informaiton """

        self.init_test(self.current_func_name)
        db = self.__create_db_instance()
        test_file = os.path.join(self.data_dir,
                                 self.current_func_name + '.txt')
        db.open_db(test_file)
        records = db.records
        test_record = records.next()
        self.assertEqual(test_record.family_code,
                         '8',
                         'Incorrect family code')
        self.assertEqual(test_record.type2,
                         'RECTAL',
                         'Incorrect family type2')
        self.assertEqual(test_record.type3,
                         '',
                         'Incorrect family type3')
        self.assertEqual(test_record.type4,
                         'CAFAM',
                         'Incorrect family type4')
        patient_codes = test_record.patient_codes
        self.assertEqual(len(patient_codes),
                         2,
                         'Incorrect number of patient codes being read')
        self.assertEqual(patient_codes[0],
                         'Co35',
                         'Incorrect patient code')
        self.assertEqual(patient_codes[1],
                         'Co37',
                         'Incorrect patient code')
        records.next()
        test_record = records.next()
        self.assertEqual(test_record.family_code,
                         '348',
                         'Incorrect family code')
        self.assertEqual(test_record.type2,
                         '',
                         'Incorrect family type2')
        self.assertEqual(test_record.type3,
                         'COLON',
                         'Incorrect family type3')
        self.assertEqual(test_record.type4,
                         '',
                         'Incorrect family type4')
        patient_codes = test_record.patient_codes
        self.assertEqual(len(patient_codes),
                         2,
                         'Incorrect number of patient codes being read')
        self.assertEqual(patient_codes[0],
                         'Co846',
                         'Incorrect patient code')
        self.assertEqual(patient_codes[1],
                         'Co857',
                         'Incorrect patient code')

